// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIFchJ-T6WX_uc9N9eYHAaRJmFFvWkYfw',
    appId: '1:316825709491:web:a07109147388bc9aa339c6',
    messagingSenderId: '316825709491',
    projectId: 'shop-d074f',
    authDomain: 'shop-d074f.firebaseapp.com',
    storageBucket: 'shop-d074f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6do_S0xRSoWO0f7vxXb5DEk7Ad0PQbxU',
    appId: '1:316825709491:android:2a450650b1b03284a339c6',
    messagingSenderId: '316825709491',
    projectId: 'shop-d074f',
    storageBucket: 'shop-d074f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2DU4tJJczye2cPNuTiap9vhX58aFWGY',
    appId: '1:316825709491:ios:62cc343f8b6d4ceca339c6',
    messagingSenderId: '316825709491',
    projectId: 'shop-d074f',
    storageBucket: 'shop-d074f.appspot.com',
    iosClientId: '316825709491-cq4v3pkjdvtak1dr59r051nd46eea5q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu2DU4tJJczye2cPNuTiap9vhX58aFWGY',
    appId: '1:316825709491:ios:62cc343f8b6d4ceca339c6',
    messagingSenderId: '316825709491',
    projectId: 'shop-d074f',
    storageBucket: 'shop-d074f.appspot.com',
    iosClientId: '316825709491-cq4v3pkjdvtak1dr59r051nd46eea5q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );
}
